version: '3.8'

services:
  promptsmith:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - LOG_LEVEL=debug
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --appendonly yes

  # Optional: Redis Commander for debugging
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"
    depends_on:
      - redis
    profiles:
      - debug

  # Auto-fix agent service
  auto-fixer:
    build:
      context: .
      dockerfile: Dockerfile.auto-fixer
    environment:
      - NODE_ENV=development
      - REDIS_URL=redis://redis:6379
    env_file:
      - .env
    depends_on:
      - redis
      - promptsmith
    volumes:
      - ./tools:/app/tools
      - ./test-mcps:/app/test-mcps
      - ./src:/app/src
    profiles:
      - auto-fix

volumes:
  redis_data:

networks:
  default:
    name: promptsmith-network