groups:
  - name: promptsmith
    rules:
      - alert: PromptSmithDown
        expr: up{job="promptsmith"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "PromptSmith service is down"
          description: "PromptSmith has been down for more than 1 minute"

      - alert: HighErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) > 0.1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High error rate detected"
          description: "Error rate is above 10% for 5 minutes"

      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 1
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High response time detected"
          description: "95th percentile response time is above 1 second"
