global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'promptsmith-monitor'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: 'promptsmith'
    static_configs:
      - targets: ['promptsmith:3000']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    
  - job_name: 'glitchtip'
    static_configs:
      - targets: ['glitchtip:8000']
    metrics_path: '/metrics'

  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    metrics_path: '/metrics'

  - job_name: 'mcp-inspector'
    static_configs:
      - targets: ['mcp-inspector:6274']
    metrics_path: '/metrics'
    scrape_interval: 5s